[2022-03-21 10:12:07,422] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.write_to_postgres 2022-03-20T00:00:00+00:00 [queued]>
[2022-03-21 10:12:07,436] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.write_to_postgres 2022-03-20T00:00:00+00:00 [queued]>
[2022-03-21 10:12:07,436] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 10:12:07,436] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-03-21 10:12:07,436] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 10:12:07,452] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): write_to_postgres> on 2022-03-20T00:00:00+00:00
[2022-03-21 10:12:07,455] {standard_task_runner.py:52} INFO - Started process 1201 to run task
[2022-03-21 10:12:07,459] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_news', 'write_to_postgres', '2022-03-20T00:00:00+00:00', '--job-id', '523', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_news.py', '--cfg-path', '/tmp/tmp2ipuci5k', '--error-file', '/tmp/tmp2rd4257y']
[2022-03-21 10:12:07,460] {standard_task_runner.py:77} INFO - Job 523: Subtask write_to_postgres
[2022-03-21 10:12:07,508] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_news.write_to_postgres 2022-03-20T00:00:00+00:00 [running]> on host e39215f0be5b
[2022-03-21 10:12:07,578] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_news
AIRFLOW_CTX_TASK_ID=write_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-03-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-20T00:00:00+00:00
[2022-03-21 10:12:07,578] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: 'tmp_2022-03-20_2022-03-21/news_nvidia.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_news.py", line 59, in _execute_query_with_hook
    with open(sql_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_2022-03-20_2022-03-21/news_nvidia.sql'
[2022-03-21 10:12:07,580] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_news, task_id=write_to_postgres, execution_date=20220320T000000, start_date=20220321T101207, end_date=20220321T101207
[2022-03-21 10:12:07,633] {local_task_job.py:146} INFO - Task exited with return code 1
