[2022-03-20 21:14:52,323] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.write_to_postgres 2022-03-19T00:00:00+00:00 [queued]>
[2022-03-20 21:14:52,335] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.write_to_postgres 2022-03-19T00:00:00+00:00 [queued]>
[2022-03-20 21:14:52,335] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 21:14:52,335] {taskinstance.py:1043} INFO - Starting attempt 9 of 9
[2022-03-20 21:14:52,335] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 21:14:52,356] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): write_to_postgres> on 2022-03-19T00:00:00+00:00
[2022-03-20 21:14:52,363] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_news', 'write_to_postgres', '2022-03-19T00:00:00+00:00', '--job-id', '323', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_news.py', '--cfg-path', '/tmp/tmpepfi5tnu', '--error-file', '/tmp/tmp08c5dn0a']
[2022-03-20 21:14:52,364] {standard_task_runner.py:77} INFO - Job 323: Subtask write_to_postgres
[2022-03-20 21:14:52,360] {standard_task_runner.py:52} INFO - Started process 642 to run task
[2022-03-20 21:14:52,425] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_news.write_to_postgres 2022-03-19T00:00:00+00:00 [running]> on host e39215f0be5b
[2022-03-20 21:14:52,461] {taskinstance.py:1455} ERROR - news_nvidia_{{ ds }}_{{ next_ds }}.sql
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1249, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1750, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 859, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 872, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 907, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: news_nvidia_{{ ds }}_{{ next_ds }}.sql
[2022-03-20 21:14:52,463] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_news, task_id=write_to_postgres, execution_date=20220319T000000, start_date=20220320T211452, end_date=20220320T211452
[2022-03-20 21:14:52,501] {local_task_job.py:146} INFO - Task exited with return code 1
