[2022-03-20 21:03:38,163] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.prepare_insert 2022-03-19T00:00:00+00:00 [queued]>
[2022-03-20 21:03:38,175] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.prepare_insert 2022-03-19T00:00:00+00:00 [queued]>
[2022-03-20 21:03:38,175] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 21:03:38,175] {taskinstance.py:1043} INFO - Starting attempt 8 of 8
[2022-03-20 21:03:38,175] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 21:03:38,189] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): prepare_insert> on 2022-03-19T00:00:00+00:00
[2022-03-20 21:03:38,192] {standard_task_runner.py:52} INFO - Started process 608 to run task
[2022-03-20 21:03:38,196] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_news', 'prepare_insert', '2022-03-19T00:00:00+00:00', '--job-id', '310', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_news.py', '--cfg-path', '/tmp/tmpg06sbmp7', '--error-file', '/tmp/tmpgltf57xy']
[2022-03-20 21:03:38,196] {standard_task_runner.py:77} INFO - Job 310: Subtask prepare_insert
[2022-03-20 21:03:38,239] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_news.prepare_insert 2022-03-19T00:00:00+00:00 [running]> on host e39215f0be5b
[2022-03-20 21:03:38,280] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_news
AIRFLOW_CTX_TASK_ID=prepare_insert
AIRFLOW_CTX_EXECUTION_DATE=2022-03-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-19T00:00:00+00:00
[2022-03-20 21:03:38,281] {taskinstance.py:1455} ERROR - 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_news.py", line 43, in _prepare_insert
    IMG_URL = fmt_ins(art['urlToImage'])
  File "/opt/airflow/dags/fetch_news.py", line 27, in fmt_ins
    s = s.replace("'", '"')
AttributeError: 'NoneType' object has no attribute 'replace'
[2022-03-20 21:03:38,283] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_news, task_id=prepare_insert, execution_date=20220319T000000, start_date=20220320T210338, end_date=20220320T210338
[2022-03-20 21:03:38,329] {local_task_job.py:146} INFO - Task exited with return code 1
