[2022-03-20 20:22:52,832] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_postgress.create_pet_table 2022-03-20T20:22:51.791889+00:00 [queued]>
[2022-03-20 20:22:52,849] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_postgress.create_pet_table 2022-03-20T20:22:51.791889+00:00 [queued]>
[2022-03-20 20:22:52,849] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 20:22:52,849] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-03-20 20:22:52,849] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 20:22:52,858] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2022-03-20T20:22:51.791889+00:00
[2022-03-20 20:22:52,864] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test_postgress', 'create_pet_table', '2022-03-20T20:22:51.791889+00:00', '--job-id', '116', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_postgress.py', '--cfg-path', '/tmp/tmpdziw0afv', '--error-file', '/tmp/tmpzf_2iilk']
[2022-03-20 20:22:52,861] {standard_task_runner.py:52} INFO - Started process 56 to run task
[2022-03-20 20:22:52,864] {standard_task_runner.py:77} INFO - Job 116: Subtask create_pet_table
[2022-03-20 20:22:52,897] {logging_mixin.py:104} INFO - Running <TaskInstance: test_postgress.create_pet_table 2022-03-20T20:22:51.791889+00:00 [running]> on host e39215f0be5b
[2022-03-20 20:22:52,930] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_postgress
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-20T20:22:51.791889+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-20T20:22:51.791889+00:00
[2022-03-20 20:22:52,931] {postgres.py:69} INFO - Executing: 
            insert into NEWS.NEWS_COMPANY(COMPANY)
            values ('asd')
          
[2022-03-20 20:22:52,945] {taskinstance.py:1455} ERROR - The conn_id `postgres_default` isn't defined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 83, in get_conn
    conn = self.connection or self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 63, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 354, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2022-03-20 20:22:52,947] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=test_postgress, task_id=create_pet_table, execution_date=20220320T202251, start_date=20220320T202252, end_date=20220320T202252
[2022-03-20 20:22:52,997] {local_task_job.py:146} INFO - Task exited with return code 1
