[2022-03-21 16:01:36,139] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_postgress.python_task 2022-03-21T16:01:35.122987+00:00 [queued]>
[2022-03-21 16:01:36,155] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_postgress.python_task 2022-03-21T16:01:35.122987+00:00 [queued]>
[2022-03-21 16:01:36,155] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 16:01:36,155] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-03-21 16:01:36,155] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 16:01:36,163] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): python_task> on 2022-03-21T16:01:35.122987+00:00
[2022-03-21 16:01:36,166] {standard_task_runner.py:52} INFO - Started process 1495 to run task
[2022-03-21 16:01:36,170] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test_postgress', 'python_task', '2022-03-21T16:01:35.122987+00:00', '--job-id', '634', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_postgress.py', '--cfg-path', '/tmp/tmpym7d24kj', '--error-file', '/tmp/tmplnnp64lx']
[2022-03-21 16:01:36,171] {standard_task_runner.py:77} INFO - Job 634: Subtask python_task
[2022-03-21 16:01:36,216] {logging_mixin.py:104} INFO - Running <TaskInstance: test_postgress.python_task 2022-03-21T16:01:35.122987+00:00 [running]> on host e39215f0be5b
[2022-03-21 16:01:36,262] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_postgress
AIRFLOW_CTX_TASK_ID=python_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-21T16:01:35.122987+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-21T16:01:35.122987+00:00
[2022-03-21 16:01:36,272] {base.py:74} INFO - Using connection to: id: news_in. Host: postgres, Port: 5432, Schema: , Login: airflow, Password: XXXXXXXX, extra: None
[2022-03-21 16:01:36,277] {taskinstance.py:1455} ERROR - 'NoneType' object has no attribute 'fetchall'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_postgress.py", line 13, in _select_all_platforms
    res = cursor.execute('select * from TARGET_SEARCH').fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'
[2022-03-21 16:01:36,278] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=test_postgress, task_id=python_task, execution_date=20220321T160135, start_date=20220321T160136, end_date=20220321T160136
[2022-03-21 16:01:36,304] {local_task_job.py:146} INFO - Task exited with return code 1
