[2022-03-20 15:01:06,036] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.dowload_desc 2022-03-07T00:00:00+00:00 [queued]>
[2022-03-20 15:01:06,051] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.dowload_desc 2022-03-07T00:00:00+00:00 [queued]>
[2022-03-20 15:01:06,051] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 15:01:06,051] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-03-20 15:01:06,052] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 15:01:06,082] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): dowload_desc> on 2022-03-07T00:00:00+00:00
[2022-03-20 15:01:06,085] {standard_task_runner.py:52} INFO - Started process 54 to run task
[2022-03-20 15:01:06,093] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_news', 'dowload_desc', '2022-03-07T00:00:00+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_news.py', '--cfg-path', '/tmp/tmpkga8gjih', '--error-file', '/tmp/tmp67n_wm7t']
[2022-03-20 15:01:06,094] {standard_task_runner.py:77} INFO - Job 10: Subtask dowload_desc
[2022-03-20 15:01:06,201] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_news.dowload_desc 2022-03-07T00:00:00+00:00 [running]> on host 0b08bfee94e8
[2022-03-20 15:01:06,263] {taskinstance.py:1455} ERROR - unexpected '}'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1249, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1750, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 859, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 872, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 909, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
[2022-03-20 15:01:06,265] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_news, task_id=dowload_desc, execution_date=20220307T000000, start_date=20220320T150106, end_date=20220320T150106
[2022-03-20 15:01:06,366] {local_task_job.py:146} INFO - Task exited with return code 1
